# Generated by Django 4.2.24 on 2025-09-25 08:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='useralertpreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='useralertpreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='delivery_type',
            field=models.CharField(choices=[('INAPP', 'In-App'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification')], default='INAPP', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='reminder_frequency',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AlterField(
            model_name='alert',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='alerts', to='alerts.team'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='alerts.alert'),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='useralertpreference',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='alerts.alert'),
        ),
        migrations.AlterField(
            model_name='useralertpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='notificationdelivery',
            unique_together={('alert', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='useralertpreference',
            unique_together={('alert', 'user')},
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_active', 'archived'], name='alerts_aler_is_acti_970501_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['start_time', 'expiry_time'], name='alerts_aler_start_t_a9ff12_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity'], name='alerts_aler_severit_202179_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['alert', 'user'], name='alerts_noti_alert_i_e46819_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['delivered_at'], name='alerts_noti_deliver_692c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='useralertpreference',
            index=models.Index(fields=['user', 'read'], name='alerts_user_user_id_14cde9_idx'),
        ),
        migrations.AddIndex(
            model_name='useralertpreference',
            index=models.Index(fields=['alert', 'user'], name='alerts_user_alert_i_264d54_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='alerts.team'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
